#!/bin/bash

if [ -d ~/Desktop/ns-3 ]
then
	cd ~/Desktop/ns-3
else
	cd ~/ns-3
fi

if [ -d stratos ]
then
	rm stratos/*.txt
else
	mkdir stratos
fi

for i in {1..30}
do
	./waf --run "stratos --nMobile=0" >> stratos/mobile_0.txt
	./waf --run "stratos --nMobile=25" >> stratos/mobile_25.txt
	./waf --run "stratos --nMobile=50" >> stratos/mobile_50.txt
	./waf --run "stratos --nMobile=100" >> stratos/mobile_100.txt

	./waf --run "stratos --nRequesters=1" >> stratos/requesters_1.txt
	./waf --run "stratos --nRequesters=2" >> stratos/requesters_2.txt
	./waf --run "stratos --nRequesters=4" >> stratos/requesters_4.txt
	./waf --run "stratos --nRequesters=8" >> stratos/requesters_8.txt
	./waf --run "stratos --nRequesters=16" >> stratos/requesters_16.txt
	./waf --run "stratos --nRequesters=24" >> stratos/requesters_24.txt
	./waf --run "stratos --nRequesters=32" >> stratos/requesters_32.txt

	./waf --run "stratos --nServices=1" >> stratos/services_1.txt
	./waf --run "stratos --nServices=2" >> stratos/services_2.txt
	./waf --run "stratos --nServices=4" >> stratos/services_4.txt
	./waf --run "stratos --nServices=8" >> stratos/services_8.txt

	#./waf --run "stratos --nPackets=1" >> stratos/packets_1.txt
	./waf --run "stratos --nPackets=10" >> stratos/packets_10.txt
	./waf --run "stratos --nPackets=20" >> stratos/packets_20.txt
	./waf --run "stratos --nPackets=40" >> stratos/packets_40.txt
	./waf --run "stratos --nPackets=60" >> stratos/packets_60.txt
done